<template>
  <div>
    <h2>Creations</h2>
    
    <h3>Games</h3>
    <p>I've started game development in 2016. I'm making short games, mostly for the web. Some have been made during 48 hours jams. You cn find the entire list of them on <a href="https://itooh.itch.io">itch.io</a></p>

    <ul>
      <li v-for="game in games">
        <project-link v-bind="game"></project-link>
      </li>
    </ul>

    <h3>Experiments</h3>
    <p>These are personal creations made to test or learn various technologies.</p>

    <ul>
      <li v-for="experiment in experiments">
        <project-link v-bind="experiment"></project-link>
      </li>
    </ul>

    <h3>Videos (French)</h3>
    <p>In 2015, I started making videos for Youtube. At the time it was mostly experimental: I tried doing sketches, essays, game analysis… With a schedule of one video per week, my goal was to learn this medium and explore what I could do. Some of the results are bad, some are absolutely terrible, and a few are actually still pretty okay.</p>
    <p>In 2017, I decided to focus myself on game-design videos. Since I've been doing essays about independant games, strange creations, and original usages of the game medium. My goal is to bring reflexions on how we define video-game, show how it can be used in new and creative ways, and share thoughts on some unknown games.</p>
    <p>As stated, those videoas are only in French. They can be seen on the channel <a>Excursions Virtuelles</a>.</p>

  </div>
</template>

<script>
import ProjectLink from './ProjectLink';

export default {
  name: 'creations',
  data() {
    return {
      games: [
        {
          title: 'Moog Memories',
          url: 'https://itooh.itch.io/moog-memories',
          description: 'Interactive music in HTML5, made in 48 hours for the Game Music Jam',
        },
        {
          title: 'Tabletop Dance',
          url: 'https://itooh.itch.io/tabletop-dance',
          description: 'Puzzle shooter made during the GMTK Jam',
        },
        {
          title: 'Safe Bots',
          url: 'https://itooh.itch.io/safe-bots',
          description: 'Puzzle game made in one week',
        },
        {
          title: 'Deep Sea School',
          url: 'https://itooh.itch.io/deep-sea-school',
          description: 'Exploration and narration game',
        },
      ],
      experiments: [
        {
          title: 'Landscape of sounds',
          url: 'https://github.com/ClementRivaille/landscape-of-sounds',
          description: 'Generative music procedurally generated by the Web Audio API',
        },
        {
          title: 'Harmon\'it',
          url: 'https://github.com/ClementRivaille/harmon-it',
          description: 'Application displaying chords, made in React Redux',
        },
        {
          title: 'Once Upon Nothing',
          url: 'https://github.com/ClementRivaille/once-upon-nothing',
          description: 'Random sentence generator, in Angular 2',
        },
        {
          title: 'Terrible logos',
          url: 'https://github.com/ClementRivaille/terrible-logos',
          description: 'Weirdly styled text, using BEM methodology',
        },
      ],
    };
  },
  components: { ProjectLink },
};
</script>

<style>
</style>
